Get songs
GSG-G7/Your-Lyrics pull request #48
Opened 2019-08-01 07:49 UTC by Asmaathabet

2019-08-02 09:10 UTC, yosefanajjar requested changes
In the getSongsNames file, you didn't hide the API key, so you need to include a .env file and put an enviroment variable in it so you can call it in that page after you require the dotenv/config

2019-08-02 16:29 UTC, yosefanajjar approved these changes
Well done , great work

2019-08-03 14:23 UTC, MaiUbeid approved these changes

2019-08-04 05:53 UTC, asem1789 approved these changes

2019-08-04 05:56 UTC, merged